{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comfyui-3d-pack.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "comfyui-3d-pack.labels" . | nindent 4 }}
type: Opaque
stringData:
  huggingface-token: {{ .Values.secrets.huggingfaceToken | quote }}
  api-keys: {{ .Values.secrets.apiKeys | quote }}
{{- end }}
---
{{- if and .Values.objectStorage.enabled (not .Values.objectStorage.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-object-storage" (include "comfyui-3d-pack.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "comfyui-3d-pack.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.objectStorage.accessKey | quote }}
  secret-key: {{ .Values.objectStorage.secretKey | quote }}
{{- end }}
